# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular

  # Bold font face
  bold:
    family: "JetBrainsMono Nerd Font"

  # Italic font face
  italic:
    family: "JetBrainsMono Nerd Font"
    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    family: "JetBrainsMono Nerd Font"

  # Point size
  size: 9.0